---
type: Handler
api_version: core/v2
metadata:
  name: influxdb
  namespace: default
spec:
  type: pipe
  command: "sensu-influxdb-handler -a 'http://influxdb:8086' -d 'sensu' -u 'admin' -p 'admin'"
  timeout: 10
  mutator: event-enrichment
  runtime_assets:
  - sensu-influxdb-handler
