---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: sensu_asset_index_response
spec:
  command: check_http -H sensu-asset-server -N
  runtime_assets:
  - nagios-check-http-v0.1
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: nagios_perfdata
  output_metric_handlers:
  - influxdb
