---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: http_service
  labels:
    aggregate: http_service
spec:
  command: echo 'http_service value='`echo $RANDOM`' '`date +%s`
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
